name: Build and deploy to Kubernetes
on:
  workflow_dispatch:
    inputs:
      worker-qty:
        description: Quantity of worker replicas
        required: true
env:
  APP_VERSION: ${{ github.run_id }}
  WORKER_QTY: ${{ github.event.inputs.worker-qty }}
jobs:
  build-main:
    name: Build main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: main/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.MAIN_IMAGE_NAME }}:${{ env.APP_VERSION }}
  build-worker:
    name: Build worker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: worker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.WORKER_IMAGE_NAME }}:${{ env.APP_VERSION }}
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: [ build-main, build-worker ]
    steps:
      - uses: actions/checkout@master
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/aks-set-context@v3
        with:
          resource-group: '${{ secrets.AKS_RESOURCE_GROUP }}'
          cluster-name: '${{ secrets.AKS_CLUSTER_NAME }}'
      - name: Configure templates
        run: envsubst < ./k8s/templates/main-deployment.yaml.template > ./k8s/main-deployment.yaml
      - name: Configure templates
        run: envsubst < ./k8s/templates/worker-deployment.yaml.template > ./k8s/worker-deployment.yaml
      - run: cat ./k8s/main-deployment.yaml
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v4
        with:
          manifests: |
            ./k8s/main-deployment.yaml
            ./k8s/worker-deployment.yaml
            ./k8s/lb-deployment.yaml